export enum MERCHANT_ENUMS {
  BECOME_MERCHANT = "BECOME_MERCHANT",
  COMPLETE_MERCHANT_REGISTRATION = "COMPLETE_MERCHANT_REGISTRATION",
  SWITCH_AS_MERCHANT = "SWITCH_AS_MERCHANT",
  SWITCH_BACK_TO_USER = "SWITCH_BACK_TO_USER",
}
